### PR TITLE
fix to use Scala 2.12

### PR DESCRIPTION
**Pull request by smeagol74**
fixing this issue #100

### CODE REVIEW

**Comment by jesseeichar** [comment]
Thank you very much for this!

**Comment by smeagol74** [comment]
Ouch, you've merged it directly to 2.11.x branch? I supposed you've create 2.12.x branch and merge it there...

**Comment by jesseeichar** [comment]
hmmm.  I didn't notice the too branch... I'll fix that up in a few minutes

**Comment by rtyley** [comment]
Are you able to make a release to Maven Central of this new version?

I just want to say that as far as I can tell, this is still the best IO library available for Scala- beating newcomers like `rapture-io` on both documentation and features (eg ability to control terminator-processing behaviour when reading lines from a source). I don't know if scala-io is still core to your interests, but I notice that there are a few places the build-related infrastructure on this project could be brought up to date, eg: sbt 1.0.0, use sbt-release & sbt-sonatype to automate the release process, also perhaps https://github.com/tpolecat/tut to replace the current custom doc build with a process allowing you to write documentation that is typechecked _and_ run as part of your build. I could drop some time into that aspect of things if it sounds helpful?

**Comment by rtyley** [comment]
I've released a cut of this project, based off https://github.com/jesseeichar/scala-io/commit/2bd04c3d0, to Maven Central, under my own group id:

* "com.madgag" %% "scala-io-core" % "0.4.9"
* "com.madgag" %% "scala-io-file" % "0.4.9"

http://search.maven.org/#search%7Cga%7C1%7Ccom.madgag%20scala-io

Note that this is only released for Scala 2.12, though I think cross-compiling it for Scala 2.11 wouldn't be a tricky thing to achieve.

**Pull request merged**
